using System;

namespace ZDragon.Project.Templates {
    public static class EndpointTemplates {


        public static Func<string, string> Default = (name) => {
            return $@"

# {name}

This is the {name} endpoint as generated by the ZDragon engine.

endpoint GetPersonById :: PersonId -> Person =
    Name: Get person by Id
    Description: Get's a person by a unique
        Identifier.

@ The person Id
type PersonId = Guid;

@ The person type
record Person =
    Id: PersonId;
    Name: String;
";
        };
    }
}
