using Compiler;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace ZDragon.Project.Components {
    public class ApplicationInteractor: IEquatable<ApplicationInteractor> {
        public string RootPath { get; }

        [JsonIgnore]
        public DirectoryInfo DirectoryInfo { get; }
        public string FullPath { get; }
        public string Name { get; }
        public string Namespace { get; }

        /*
         * Architecturally speaking; an application consists of:
         *  * Components
         *  * EndPoints
         *  * Databases
         *  * Models
         * 
         */
        public string ComponentsPath { get; }
        public string EndpointsPath { get; }
        public string DatabasesPath { get; }
        public string ModelsPath { get; }

        public List<ModuleInteractor> Modules { get; } = new List<ModuleInteractor>();

        public ApplicationInteractor(string root, string path, CompilationCache cache) : this(root, new DirectoryInfo(path), cache) {
            //
        }

        /// <summary>
        /// Default Constructor
        /// </summary>
        /// <param name="dir"></param>
        public ApplicationInteractor(string root, DirectoryInfo dir, CompilationCache cache) {
            this.RootPath = root;
            this.DirectoryInfo = dir;
            this.FullPath = dir.FullName;
            this.Name = dir.Name;

            this.Namespace = Utilities.GetNamespaceFromPath(this.RootPath, dir.FullName);

            this.ComponentsPath = Path.Join(this.FullPath, "Components");
            this.EndpointsPath = Path.Join(this.FullPath, "Endpoints");
            this.DatabasesPath = Path.Join(this.FullPath, "Databases");
            this.ModelsPath = Path.Join(this.FullPath, "Models");

            if (!Directory.Exists(this.ComponentsPath)) Directory.CreateDirectory(this.ComponentsPath);
            if (!Directory.Exists(this.EndpointsPath)) Directory.CreateDirectory(this.EndpointsPath);
            if (!Directory.Exists(this.DatabasesPath)) Directory.CreateDirectory(this.DatabasesPath);
            if (!Directory.Exists(this.ModelsPath)) Directory.CreateDirectory(this.ModelsPath);

            foreach (var file in Directory.GetFiles(this.FullPath)) {
                Modules.Add(new ModuleInteractor(this.RootPath, file, cache));
            }
            foreach (var file in Directory.GetFiles(this.ComponentsPath)) {
                Modules.Add(new ModuleInteractor(this.RootPath, file, cache));
            }
            foreach (var file in Directory.GetFiles(this.EndpointsPath)) {
                Modules.Add(new ModuleInteractor(this.RootPath, file, cache));
            }
            foreach (var file in Directory.GetFiles(this.DatabasesPath)) {
                Modules.Add(new ModuleInteractor(this.RootPath, file, cache));
            }
            foreach (var file in Directory.GetFiles(this.ModelsPath)) {
                Modules.Add(new ModuleInteractor(this.RootPath, file, cache));
            }
        }

        public void Verify() {
            foreach (var module in Modules) module.Verify();
        }

        public ModuleInteractor Find(string ns) {
            return Modules.FirstOrDefault(m => m.Namespace == ns);
        }

        public static List<ApplicationInteractor> FromDirectory(string root, string path, CompilationCache cache) {
            
            var applications = new List<ApplicationInteractor>();
            if (Directory.Exists(path)) {
                var directory = new DirectoryInfo(path);
                foreach (var dir in directory.GetDirectories()) {
                    applications.Add(new ApplicationInteractor(root, dir, cache));
                }
            }

            return applications;
        }

        public static ApplicationInteractor Create(string root, string name, CompilationCache cache) {
            var fullPath = Path.Combine(Path.GetFullPath(root), name);

            // either create or load the ApplicationInteractor
            DirectoryInfo dirInfo =
                Directory.Exists(fullPath) ?
                    new DirectoryInfo(fullPath) :
                    Directory.CreateDirectory(fullPath);
            return new ApplicationInteractor(root, dirInfo, cache);        }

        public bool Equals(ApplicationInteractor other) {
            return other.FullPath == this.FullPath;
        }

        public ApplicationInteractor CreateComponent(string name) {
            var _name = name.Replace(" ", "_");
            var stream = File.Create(Path.Combine(this.ComponentsPath, $"{_name}.car"));
            StreamWriter writer = new StreamWriter(stream);
            writer.Write($@"

# {_name}

This is the default component as generated by the ZDragon engine.

person User =
    Name: Application User
    Interactions: 
        - {_name}

component {_name} =
    Name: {_name}
    Description: A default component description
        Please read the ZDragon language documentation 
        to see how you can maintain this component!
    Interactions:
        - Database

component Database =
    Name: My Database
    Type: Database
    

system Cloud =
    Name: My Cloud
    Description: A cloud wrapper over a set
        of components.
    Contains: 
        - {_name}
        - Database

");
            writer.Flush();
            writer.Close();
            writer.Dispose();

            return this;
        }

        public ApplicationInteractor CreateEndpoint(string name) {
            var _name = name.Replace(" ", "_");
            var stream = File.Create(Path.Combine(this.EndpointsPath, $"{_name}.car"));
            StreamWriter writer = new StreamWriter(stream);
            writer.Write($@"

# {_name}

This is the {_name} endpoint as generated by the ZDragon engine.

endpoint GetPersonById :: PersonId -> Person =
    Name: Get person by Id
    Description: Get's a person by a unique
        Identifier.

@ The person Id
type PersonId = Guid;

@ The person type
record Person =
    Id: PersonId;
    Name: String;

");
            writer.Flush();
            writer.Close();
            writer.Dispose();

            return this;
        }
    }
}
