using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;

namespace ZDragon.Project.Components {
    public class ApplicationInteractor: IEquatable<ApplicationInteractor> {
        public string RootPath { get; }
        [JsonIgnore]
        public DirectoryInfo DirectoryInfo { get; }
        public string FullPath { get; }
        public string Name { get; }
        public string Namespace { get; }

        /*
         * Architecturally speaking; an application consists of:
         *  * Components
         *  * EndPoints
         *  * Databases
         *  * Models
         * 
         */

        public string ComponentsPath { get; }
        public string EndpointsPath { get; }
        public string DatabasesPath { get; }
        public string ModelsPath { get; }

        


        public ApplicationInteractor CreateComponent(string name) {
            var _name = name.Replace(" ", "_");
            var stream = File.Create(Path.Combine(this.ComponentsPath, $"{_name}.car"));
            StreamWriter writer = new StreamWriter(stream);
            writer.Write($@"

# {_name}

This is the default component as generated by the ZDragon engine.

component {_name} =
    Name: {_name}
    Description: A default component description
        Please read the ZDragon language documentation 
        to see how you can maintain this component!

");
            writer.Flush();
            writer.Close();
            writer.Dispose();

            return this;
        }

        public ApplicationInteractor CreateEndpoint(string name) {
            var _name = name.Replace(" ", "_");
            var stream = File.Create(Path.Combine(this.EndpointsPath, $"{_name}.car"));
            StreamWriter writer = new StreamWriter(stream);
            writer.Write($@"

# {_name}

This is the {_name} endpoint as generated by the ZDragon engine.

endpoint GetPersonById :: PersonId -> Person =
    Name: Get person by Id
    Description: Get's a person by a unique
        Identifier.

@ The person Id
type PersonId = Guid;

@ The person type
record Person =
    Id: PersonId;
    Name: String;

");
            writer.Flush();
            writer.Close();
            writer.Dispose();

            return this;
        }


        public ApplicationInteractor(string root, string path): this(root, new DirectoryInfo(path)) {
            //
        }

        /// <summary>
        /// Default Constructor
        /// </summary>
        /// <param name="dir"></param>
        public ApplicationInteractor(string root, DirectoryInfo dir) {
            this.RootPath = root;
            this.DirectoryInfo = dir;
            this.FullPath = dir.FullName;
            this.Name = dir.Name;

            this.Namespace = Utilities.GetNamespaceFromPath(this.RootPath, dir.FullName);

            this.ComponentsPath = Path.Join(this.FullPath, "Components");
            this.EndpointsPath = Path.Join(this.FullPath, "Endpoints");
            this.DatabasesPath = Path.Join(this.FullPath, "Databases");
            this.ModelsPath = Path.Join(this.FullPath, "Models");

            if (!Directory.Exists(this.ComponentsPath)) {
                Directory.CreateDirectory(this.ComponentsPath);
                var stream = File.Create(Path.Combine(this.ComponentsPath, "Component_001.car"));
                StreamWriter writer = new StreamWriter(stream);
                writer.Write(@"

# Component 001

This is the default component as generated by the ZDragon engine. Feel free to delete this component.

component Component001 =
    Name: Component001
    Description: The default component
        Please read the ZDragon language
        documentation to see how you can 
        create and maintain your own 
        components!

");
                writer.Flush();
                writer.Close();
                writer.Dispose();
            }
            


            if (!Directory.Exists(this.EndpointsPath)) {
                Directory.CreateDirectory(this.EndpointsPath);
                var stream = File.Create(Path.Combine(this.EndpointsPath, "GetPersonById.car"));
                StreamWriter writer = new StreamWriter(stream);
                writer.Write(@"

# Get Person - Endpoint

This is a default endpoint as generated by the ZDragon engine.

endpoint GetPersonById :: PersonId -> Person =
    Name: Get person by Id
    Description: Get's a person by a unique
        Identifier.

@ The person Id
type PersonId = Guid;

@ The person type
record Person =
    Id: PersonId;
    Name: String;

");
                writer.Flush();
                writer.Close();
                writer.Dispose();
            }

            if (!Directory.Exists(this.DatabasesPath)) Directory.CreateDirectory(this.DatabasesPath);
            if (!Directory.Exists(this.ModelsPath)) Directory.CreateDirectory(this.ModelsPath);
        }

        public static List<ApplicationInteractor> FromDirectory(string root, string path) {
            
            var applications = new List<ApplicationInteractor>();
            if (Directory.Exists(path)) {
                var directory = new DirectoryInfo(path);
                foreach (var dir in directory.GetDirectories()) {
                    applications.Add(new ApplicationInteractor(root, dir));
                }
            }

            return applications;
        }

        public static ApplicationInteractor Create(string root, string path, string name) {
            var fullPath = Path.Combine(Path.GetFullPath(path), name);

            // either create or load the ApplicationInteractor
            DirectoryInfo dirInfo =
                Directory.Exists(fullPath) ?
                    new DirectoryInfo(fullPath) :
                    Directory.CreateDirectory(fullPath);
            return new ApplicationInteractor(root, dirInfo);        }

        public bool Equals(ApplicationInteractor other) {
            return other.FullPath == this.FullPath;
        }
    }
}
